### ISSUE TITLE
Use the USERPROFILE environment variable for Windows users.

### ISSUE THREAD

**Issue by ghost** [jlvihv/BingGPT#1]
See https://github.com/jlvihv/BingGPT/pull/2.

**Comment by shawnjb** [comment]
https://github.com/jlvihv/BingGPT/pull/2

**Comment by shawnjb** [comment]
I'll have to implement a few more changes before this PR can be merged.

**Comment by jlvihv** [comment]
This is the first PR I have received, pleasant experience, thank you very much, have merged.
