### ISSUE TITLE
An entry in the Registry Editor is required for colored text to work.

### ISSUE THREAD

**Issue by ghost** [jlvihv/BingGPT#3]
Ensure that users running Windows 10 use this command in their terminal, with administrator privileges, to enable text colors in the terminal.

```cmd
reg add HKCU\Console /v VirtualTerminalLevel /t REG_DWORD /d 1
```

**Comment by jlvihv** [comment]
Added to [README](https://github.com/jlvihv/BingGPT#for-windows10-users), thank you!
