### ISSUE TITLE
The program is not functioning at all.

### ISSUE THREAD

**Issue by ghost** [jlvihv/BingGPT#4]
Possibly related to a countermeasure (if any).

**Comment by jlvihv** [comment]
Yes, the program doesn't work on Chinese networks, and I'm not actively looking for a solution.  Since I've been using aichat and chatgpt-desktop for a while, and they work great, I didn't want to bother.

**Comment by ghost** [comment]
Never heard of ChatGPT-Desktop, what's that?

**Comment by jlvihv** [comment]
that's it: https://github.com/lencx/ChatGPT
